/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QrRouteImport } from './routes/qr'
import { Route as PrintQrRouteImport } from './routes/print-qr'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiExportDotcsvRouteImport } from './routes/api/export[.]csv'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminRosterRouteImport } from './routes/admin/roster'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'

const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintQrRoute = PrintQrRouteImport.update({
  id: '/print-qr',
  path: '/print-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiExportDotcsvRoute = ApiExportDotcsvRouteImport.update({
  id: '/api/export.csv',
  path: '/api/export.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRosterRoute = AdminRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/print-qr': typeof PrintQrRoute
  '/qr': typeof QrRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/api/export.csv': typeof ApiExportDotcsvRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/print-qr': typeof PrintQrRoute
  '/qr': typeof QrRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/api/export.csv': typeof ApiExportDotcsvRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/print-qr': typeof PrintQrRoute
  '/qr': typeof QrRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/api/export.csv': typeof ApiExportDotcsvRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/history'
    | '/print-qr'
    | '/qr'
    | '/admin/audit'
    | '/admin/roster'
    | '/admin/sessions'
    | '/api/export.csv'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/print-qr'
    | '/qr'
    | '/admin/audit'
    | '/admin/roster'
    | '/admin/sessions'
    | '/api/export.csv'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/history'
    | '/print-qr'
    | '/qr'
    | '/admin/audit'
    | '/admin/roster'
    | '/admin/sessions'
    | '/api/export.csv'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  PrintQrRoute: typeof PrintQrRoute
  QrRoute: typeof QrRoute
  ApiExportDotcsvRoute: typeof ApiExportDotcsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-qr': {
      id: '/print-qr'
      path: '/print-qr'
      fullPath: '/print-qr'
      preLoaderRoute: typeof PrintQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/export.csv': {
      id: '/api/export.csv'
      path: '/api/export.csv'
      fullPath: '/api/export.csv'
      preLoaderRoute: typeof ApiExportDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roster': {
      id: '/admin/roster'
      path: '/roster'
      fullPath: '/admin/roster'
      preLoaderRoute: typeof AdminRosterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminRosterRoute: typeof AdminRosterRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminRosterRoute: AdminRosterRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  HistoryRoute: HistoryRoute,
  PrintQrRoute: PrintQrRoute,
  QrRoute: QrRoute,
  ApiExportDotcsvRoute: ApiExportDotcsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
